### ISSUE TITLE
Evaluate replacing HTTP.jl with Downloads.jl

### ISSUE THREAD

**Issue by bradlo** [RelationalAI/rai-sdk-julia#11]
Due to recurring issues with HTTP.jl.

**Comment by bradlo** [comment]
closing wont fix.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-4454](https://relationalai.atlassian.net/browse/RAI-4454).

_This link is only accessible to employees of RelationalAI._
