### ISSUE TITLE
README: Pkg.add exmaple doesn't work

### ISSUE THREAD

**Issue by pabsts** [RelationalAI/rai-sdk-julia#13]
Running the first command shown in the README 
```julia
julia> using Pkg; Pkg.add("https://github.com/RelationalAI/rai-sdk-julia.git")
```
results in Julia 1.7.2 in the error:
```
ERROR: `https://github.com/RelationalAI/rai-sdk-julia.git` is not a valid package name
The argument appears to be a URL or path, perhaps you meant `Pkg.add(url="...")` or `Pkg.add(path="...")`.
```
The following succeeds:
```
Pkg.add(url="https://github.com/RelationalAI/rai-sdk-julia.git")
```

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-4538](https://relationalai.atlassian.net/browse/RAI-4538).

_This link is only accessible to employees of RelationalAI._
