### ISSUE TITLE
"show_result" MethodError

### ISSUE THREAD

**Issue by cpetitpas** [RelationalAI/rai-sdk-julia#38]
In the course of testing https://github.com/RelationalAI/raicode/issues/6046 I came across this issue wherein it seems the `show_result` method is broken.
Using Julia version 1.7.3 and `using Pkg; Pkg.add(url="https://github.com/RelationalAI/rai-sdk-julia.git")` per the documentation.
```
julia> rsp = exec(
           ctx,
           database,
           engine,
           "def a = 1;2 def b = 3;4 def output:one = a def output:two = b"
       )
Dict{String, Any} with 4 entries:
  "metadata"    => JSON3.Object[{…
  "problems"    => Union{}[]
  "results"     => Pair{String, Arrow.Table}["/:output/:two/Int64"=>Arrow.Table with 2 rows, 1 columns, and schema:…
  "transaction" => {…

julia> show_result(rsp)
ERROR: MethodError: no method matching show_result(::Dict{String, Any})
Closest candidates are:
  show_result(::IO, ::JSON3.Object) at ~/.julia/packages/RAI/nBTqc/src/results.jl:61
  show_result(::JSON3.Object) at ~/.julia/packages/RAI/nBTqc/src/results.jl:62
Stacktrace:
 [1] top-level scope
   @ REPL[27]:1
```

**Comment by NHDaly** [comment]
👍 you are correct. The `show_result()` function was only written for the v1 outputs, and we haven't rewritten it for the v2 outputs yet.

**Comment by NHDaly** [comment]
@NRHelmi has offered to implement this from the v2 response. (@NRHelmi: can you do it off the proto metadata? @bachdavi is working right now on adding proto support to this repo; can you coordinate with him on this?)

**Comment by cpetitpas** [comment]
Fix verified in https://github.com/RelationalAI/rai-sdk-julia.git (main).
Thanks @NHDaly / @NRHelmi .

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5676](https://relationalai.atlassian.net/browse/RAI-5676).

_This link is only accessible to employees of RelationalAI._
