### ISSUE TITLE
Retryable HTTP errors should be retried (to satisfaction?) before being thrown to callers

### ISSUE THREAD

**Issue by NHDaly** [RelationalAI/rai-sdk-julia#45]
https://relationalai.slack.com/archives/C013D9D5M8C/p1657572191227289?thread_ts=1657568657.610889&cid=C013D9D5M8C

For example, we recently encountered `"502 Bad Gateway"` thrown from a status check in `exec()`, after 5 hours on an expected ~40 hour transaction.

**Comment by NHDaly** [comment]
I don't know the set of all HTTP errors that can be retried, but we should enact a policy for those, and retry them a few times before eventually throwing the error to the caller.

**Comment by NHDaly** [comment]
Does the HTTP.jl package do some of this on its own? That would be worth looking into as well.

**Comment by NHDaly** [comment]
I think this is closed by #48.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5938](https://relationalai.atlassian.net/browse/RAI-5938).

_This link is only accessible to employees of RelationalAI._
