### ISSUE TITLE
drop the line to disable retries in HTTP.jl

### ISSUE THREAD

**Issue by NHDaly** [RelationalAI/rai-sdk-julia#47]
https://github.com/RelationalAI/rai-sdk-julia/blob/935d4f1fe50e675ee462e290a0d3301a2d66d0a0/src/rest.jl#L88

https://github.com/RelationalAI/rai-sdk-julia/blob/935d4f1fe50e675ee462e290a0d3301a2d66d0a0/src/rest.jl#L130

See: #45

**Comment by NHDaly** [comment]
Closed by #48

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-5949](https://relationalai.atlassian.net/browse/RAI-5949).

_This link is only accessible to employees of RelationalAI._
