### ISSUE TITLE
Update `create_database` to v2 (shouldn't require an Engine to create a database)

### ISSUE THREAD

**Issue by NHDaly** [RelationalAI/rai-sdk-julia#57]
Example code to follow:
https://github.com/RelationalAI/rai-sdk-javascript/blob/fdbf90dd33cd3de52f47aa1251d0c60b597e1551/src/api/database/databaseApi.ts#L30-L39

**Comment by NHDaly** [comment]
And ideally we should add the related functionalities:
- list databases
- get database
- delete database

https://github.com/RelationalAI/rai-sdk-javascript/blob/fdbf90dd33cd3de52f47aa1251d0c60b597e1551/src/api/database/databaseApi.ts#L41-L60

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6214](https://relationalai.atlassian.net/browse/RAI-6214).

_This link is only accessible to employees of RelationalAI._
