### ISSUE TITLE
Update `create_database()` to be synchronous.

### ISSUE THREAD

**Issue by ary** [RelationalAI/rai-sdk-julia#59]
We probably shouldn't require users to write their own logic to handle the currently asynchronous nature of `create_database()`, as shown in the [examples here](https://github.com/RelationalAI/rai-sdk-julia/blob/main/examples/create-database.jl#L28). The function should do its own internal polling, perhaps the same way the example currently does it and expose a synchronous interface to the user.

**Comment by NHDaly** [comment]
Oh, apparently create_database already _is_ synchronous now! The v2 create-db operation is implemented as a synchronous operation at the API layer, so there's no polling necessary from the client! 😮 

So I think we can close this actually, now that we've merged #61; we just need to update to the engineless create-database call

**Comment by NHDaly** [comment]
@ary: i've updated the examples to show this. I've assigned you PR #64 for it 😊 thanks!

**Comment by ary** [comment]
Reviewed and approved 🕺

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6311](https://relationalai.atlassian.net/browse/RAI-6311).

_This link is only accessible to employees of RelationalAI._
