### ISSUE TITLE
Printing Config object prints credentials

### ISSUE THREAD

**Issue by rbvermaa** [RelationalAI/rai-sdk-julia#63]
It would be nicer and have less chance of exposing secrets, when secrets/credentials are not printed, similar to the old SDK.

**Comment by NRHelmi** [comment]
> do you mean when the user prints the config object, or is there some other place this shows up in the sdk?

I think @rbvermaa means the first option, for the old julia sdk I remember people copy/paste their configs through slack discussion for debugging purposes so this might be a similar case scenario, @bradlo what do you think ?

**Comment by rbvermaa** [comment]
Apologies for not being clear in the original post. As @NRHelmi mentions, I am talking about the behavior that when a user prints the object, the default display behavior shows the credentials. We've had a number of instances where people were sharing log output where this was printed and shared. In the old SDK, we have a custom display function for the config object that contains credentials, which cuts of the credentials, so that they are not (fully) exposed.

**Comment by rbvermaa** [comment]
Example from the old SDK (the listed credentials are fake):

```
julia> using RelationalAIManagement

julia> c = ManagementConnection(profile="cd")
ManagementConnection("https", "azure.relationalai.com", 443, :AZURE, Symbol("us-east"), (fLvChATldLz0mzFIK2zlXd4Gxts7kRiV, X6D...), true, Dict{String, String}())

```

**Comment by NHDaly** [comment]
From discussion: the user should still be _able to_ print the credentials if they _want to_, but they shouldn't accidentally be displayed when the object is displayed at the REPL.

@NRHelmi: to support this distinction, you should add separate overloads for the two separate printing methods:
- the 3-arg show method: `Base.show(io::IO, ::MIME"text/plain", credentials::ClientCredentials)`
    - this should _obfuscate the credentials_
- the 2-arg print method: `Base.print(io::IO, credentials::ClientCredentials)`
    - this should print them like normal.
- the 2-arg show method: `Base.show(io::IO, credentials::ClientCredentials)`
    - what should this one do?

**Comment by rbvermaa** [comment]
@NHDaly FYI, in the old SDK, print also prints them obfuscated by default. When a user wants to print the secret, they can print the attribute with the client_secret, e.g.:
```
julia> c.creds.client_secret
"X6DMYSECRETMYSECRETMYSECRET"
```

**Comment by NHDaly** [comment]
Yeah, that's a good point. @bradlo: ^ would that satisfy your concerns?

**Comment by NRHelmi** [comment]
for the old julia sdk this is what we are using: https://github.com/RelationalAI/raicode/blob/master/packages/RelationalAIManagement/src/creds.jl#L35-L54
We can add similar thing @NHDaly what do you think ?

**Comment by NRHelmi** [comment]
Resolved in this PR https://github.com/RelationalAI/rai-sdk-julia/pull/66

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6370](https://relationalai.atlassian.net/browse/RAI-6370).

_This link is only accessible to employees of RelationalAI._
