### ISSUE TITLE
Transaction Cancelation missing

### ISSUE THREAD

**Issue by afgambin** [RelationalAI/rai-sdk-julia#68]
Unlike in other SDKs, I think this functionality is still missing in this one. I could not find examples or related functions to it.

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6433](https://relationalai.atlassian.net/browse/RAI-6433).

_This link is only accessible to employees of RelationalAI._
